<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Steamworks.NET"><HintPath>../../external/workshop-uploader/Steamworks.NET.dll</HintPath></Reference>
    <None Include="../../external/workshop-uploader/steam_api64.dll" Link="steam_api64.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../external/workshop-uploader/steam_appid.txt" Link="steam_appid.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
