#pragma once
// Generated by tools/generate_localizations.ps1; edit src/localization/strings.json.
namespace prf_locale {
struct ButtonText { const wchar_t* language; const wchar_t* text; };
inline constexpr ButtonText buttons[]{
    {L"en", L"Deposit all eggs"},
    {L"zh-Hans", L"投入所有蛋"},
    {L"zh-Hant", L"投入所有蛋"},
    {L"ja", L"すべてのタマゴを投入"},
    {L"fr", L"Déposer tous les œufs"},
    {L"it", L"Deposita tutte le uova"},
    {L"de", L"Alle Eier einlegen"},
    {L"es", L"Depositar todos los huevos"},
    {L"pt-BR", L"Depositar todos os ovos"},
    {L"ru", L"Загрузить все яйца"},
    {L"ko", L"모든 알 투입"},
    {L"id", L"Masukkan semua telur"},
    {L"es-419", L"Depositar todos los huevos"},
    {L"th", L"ใส่ไข่ทั้งหมด"},
    {L"tr", L"Tüm yumurtaları koy"},
    {L"vi", L"Nạp tất cả trứng"},
    {L"pl", L"Włóż wszystkie jaja"},
};
}
