param([switch]$Check)
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
$catalog=Get-Content -LiteralPath "$root/src/localization/strings.json" -Raw | ConvertFrom-Json -AsHashtable
$languages=@('en','zh-Hans','zh-Hant','ja','fr','it','de','es','pt-BR','ru','ko','id','es-419','th','tr','vi','pl')
if ($catalog.Count -ne $languages.Count) { throw 'Expected 17 game languages' }
function Emit([string]$path,[string]$text) {
    $text=$text.Replace("`r`n","`n")+"`n"
    if($Check) {
        if(!(Test-Path -LiteralPath $path) -or [IO.File]::ReadAllText($path).Replace("`r`n","`n") -cne $text) { throw "Generated file differs: $path" }
    } else {
        [IO.Directory]::CreateDirectory((Split-Path -Parent $path)) | Out-Null
        [IO.File]::WriteAllText($path,$text,[Text.UTF8Encoding]::new($false))
    }
}
$header=@('#pragma once','// Generated by tools/generate_localizations.ps1; edit src/localization/strings.json.','namespace prf_locale {','struct ButtonText { const wchar_t* language; const wchar_t* text; };','inline constexpr ButtonText buttons[]{')
foreach($lang in $languages) {
    $s=$catalog[$lang]
    if($s.Count -ne 5 -or @($s | Where-Object { $_ -isnot [string] -or [string]::IsNullOrWhiteSpace($_) }).Count) { throw "Invalid strings: $lang" }
    foreach($token in @('54','50','200','400')) { if(!$s[3].Contains($token)) { throw "Missing processor number: $lang/$token" } }
    foreach($token in @('100','500','1000')) { if(!$s[4].Contains($token)) { throw "Missing breeder number: $lang/$token" } }
    $label=$s[2].Replace('\','\\').Replace('"','\"')
    $header+='    {L"'+$lang+'", L"'+$label+'"},'
    foreach($machine in @(@('PalResourceFactoryProcessor','PRF_EggResourceProcessor',0,3),@('PalResourceFactoryAncientBreeder','PRF_ResourceBreedingFacility',1,4))) {
        $mod,$id,$name,$desc=$machine
        $data=[ordered]@{
            DT_MapObjectNameText=@{ "MAPOBJECT_NAME_$id"=$s[$name] }
            DT_BuildObjectDescText=@{ "BUILDOBJECT_DESC_$id"=$s[$desc] }
            DT_TechnologyNameText=@{ "NAME_RECIPE_$id"=$s[$name] }
            DT_TechnologyDescText=@{ "DESC_RECIPE_$id"=$s[$desc] }
        } | ConvertTo-Json -Depth 5
        Emit "$root/src/palschema/$mod/translations/$lang/strings.json" $data
        $alias=@{'zh-Hant'='zh-TW';'zh-Hans'='zh-CN';'es'='es-ES'}[$lang]
        if($alias) { Emit "$root/src/palschema/$mod/translations/$alias/strings.json" $data }
        if($lang -eq 'en') { Emit "$root/src/palschema/$mod/translations/global/strings.json" $data }
    }
}
$header+=@('};','}'); Emit "$root/native/src/LocalizedButtons.hpp" ($header -join "`n")
Write-Output "17 languages validated; building and technology names/descriptions plus deposit button. Check=$Check"
